- README.rst
Closes https://github.com/NSLS-II/sirepo-bluesky/issues/18.
> Update the Docker command used in README

- sirepo_bluesky/sirepo_bluesky.py
> added additional logging for missing nextRequestSeconds

- .travis.yml
- examples/prepare_det_env.py
- requirements-dev.txt
- requirements.txt
- sirepo_bluesky/shadow_handler.py
- sirepo_bluesky/sirepo_detector.py
- sirepo_bluesky/tests/test_sirepo_det.py
This will add Shadow3 integration into sirepo-bluesky.
@mrakitin @jklynch
> Shadow integration

- sirepo_bluesky/sirepo_detector.py
This PR adds `beam_statistics_report` to `SirepoDetector`.
> (more) Shadow integration

- .github/workflows/tests.yml
- requirements.txt
- sirepo_bluesky/sirepo_detector.py
- sirepo_bluesky/tests/test_sirepo_det.py
Added the missing parameter `sim_report_type` to the tests.
> Update tests to use sim_report_type

- docs/source/release-history.rst
Covers mostly additions from #47.
> DOC: release notes for v0.4.1

- .github/workflows/docs.yml
- .github/workflows/flake8.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/testing.yml
- .gitignore
- docs/Makefile
- docs/build-table.py
- docs/source/index.rst
- docs/source/simulations.rst
- requirements-dev.txt
The rendered page will look like this:
The links are pointing to the corresponding `sirepo-data.json` files in this repo.
Credits to https://stackoverflow.com/a/7259267 for useful hints about how to include the dynamically generated docs.
> DOC: generate information about predefined simulations dynamically

- docs/source/release-history.rst
Includes updates from #57 and #59.
> DOC: release notes for sirepo-bluesky v0.4.3

- docs/source/notebooks/elements.ipynb
Additions following https://github.com/radiasoft/sirepo/issues/3988.
> DOC: plot `BeamStatisticsReport` values

- docs/Makefile
Borrowed from @tacaswell's internal Merge Request for a different project.
> DOC: add `show` option to docs/Makefile

- sirepo_bluesky/sirepo_bluesky.py
- sirepo_bluesky/sirepo_ophyd.py
- sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py
> Initial work on grazing angle signal

- examples/prepare_det_env.py
- examples/prepare_flyer_env.py
- requirements.txt
- sirepo_bluesky/madx_flyer.py
- sirepo_bluesky/madx_handler.py
- sirepo_bluesky/shadow_detector.py
- sirepo_bluesky/sirepo_bluesky.py
- sirepo_bluesky/sirepo_flyer.py
- sirepo_bluesky/sirepo_ophyd.py
- sirepo_bluesky/srw_detector.py
- sirepo_bluesky/tests/SIREPO_SRDB_ROOT/user/testuser/madx/00000001/sirepo-data.json
- sirepo_bluesky/tests/conftest.py
- sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py
This PR adds initial support for running simulations, getting the simulation data file, and creating ophyd classes and objects for MAD-X simulations.
> Initial MAD-X integration

- requirements.txt
`scikit-image` seems to be unused.
> Remove scikit-image from requirements

- sirepo_bluesky/sirepo_bluesky.py
- sirepo_bluesky/sirepo_flyer.py
Should we add special exceptions? Like ServerError for when the issue is on the Sirepo side.
Closes #27.
> Replacing assertions with exceptions in sirepo-bluesky.py

- .github/workflows/testing.yml
- sirepo_bluesky/sirepo_ophyd.py
- sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py
This PR adds support for more models for ophyd classes/objects generation.
> Get MADX variables into ophyd objects

- docs/build-table.py
- docs/source/notebooks/madx.ipynb
- requirements-dev.txt
A follow-up PR to #91.
Updates:
- Fix the varying column widths for the table of simulations.
- Add a plot with the data from databroker for the MAD-X example.
> DOC: update MAD-X notebook

- .github/CODEOWNERS
- .github/workflows/publish-docs.yml
- .github/workflows/testing.yml
- docs/build-table.py
- docs/source/installation.rst
- docs/source/release-history.rst
- setup.py
This PR also replaces the `master` branch with `main` where applicable.
> DOC: release notes for v0.5.0

- docs/source/release-history.rst
Discovered some typos introduced via #96.
> DOC: fix spelling in release notes

- docs/source/notebooks/elements.ipynb
> DOC: Added axes labels to BSR plots

- .github/workflows/docs.yml
- .github/workflows/publish-docs.yml
- .github/workflows/testing.yml
Uses https://github.com/mrakitin/start-sirepo-action.
Based on https://docs.github.com/en/actions/creating-actions/creating-a-composite-action.
> CI: use ` start-sirepo-action` action

- .github/workflows/docs.yml
- .github/workflows/testing.yml
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/release-history.rst
- requirements-dev.txt
- requirements.txt
Release notes + additions regarding the installation of ``srwpy`` and ``shadow3`` - all from PyPI now!
This PR also changes the Sphinx theme to [furo](https://pradyunsg.me/furo/).
> Release notes for v0.6.1

- setup.py
- sirepo_bluesky/tests/test_converter.py
- sirepo_bluesky/utils/json_yaml_converter.py
> Created .json and .yaml exporters and tests

- scripts/start_sirepo.sh
Fixes issue where Mad-X simulations weren't being properly displayed.
> Bugfix react frontend

- sirepo_bluesky/sirepo_ophyd.py
I did not have enough time to finish this project before the end of my SULI internship, but this is a draft of a function that will take elements from multiple beamlines and combine them in a copy of an empty simulation.
> Generate beamline elements draft

- docs/source/overview.rst
> DOC: minor typo correction
