NSLS-II/sirepo-bluesky

examples/Vagrantfile

The second commit here adds ports mapping for the EPICS IOC (see https://github.com/NSLS-II-TES/profile_simulated_hardware/pull/1 for details) and MongoDB for databroker.

Add a Vagrantfile for the Sirepo VirtualBox VM

---

README.rst

The instructions had a wrong name of the pip-installable package. Also, separating the clonning steps.

DOC: fix the installation instructions in README.rst

---

pytest.ini

Reported by @jklynch earlier via DM:
```py
sirepo_bluesky/tests/test_sirepo_det.py:50
/home/vagrant/nslsii-org-forks/sirepo-bluesky-fork/sirepo_bluesky/tests/test_sirepo_det.py:50: PytestUnknownMarkWarning: Unknown pytest.mark.docker - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
@pytest.mark.docker
```
Following the instructions from https://docs.pytest.org/en/stable/mark.html to make it compliant.

TST: add pytest.ini

---

.travis.yml
README.rst
sirepo_bluesky/sirepo_detector.py
sirepo_bluesky/tests/test_sirepo_det.py
sirepo_bluesky/tests/test_sirepo_flyer.py

This PR proposes an update to the original databroker integration in `SirepoDetector`, which is not compatible with the most recent databroker release.
The original calls to `insert_resource(...)` and `insert_datum(...)` are replaced with a standard `collect_asset_docs(...)`. In addition the original `image` Signal is replaced with a new ExternalFileReference.
Closes #7, #17, and #19.

Use collect_asset_docs() for resource and datum documents

---

sirepo_bluesky/sirepo_bluesky.py

Added an API to access the list of simulations for the authenticated user. Example usage:
```python
from sirepo_bluesky.sirepo_bluesky import SirepoBluesky
sim_id = 'maDwjYWE'
sb = SirepoBluesky('http://localhost:8000')
data, schema = sb.auth('srw', sim_id)
for sim in sb.simulation_list():
print('\n\t'.join(['{}', 'name: {}', 'folder: {}', 'isExample: {}']).format(
sim['simulationId'], sim['name'], sim['folder'], sim['isExample'],
))
```

added SirepoBluesky.simulation_list()

---

.github/CODEOWNERS

I am proposing to have a list of people in the `CODEOWNERS` file (see the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for details). This way the whole team will be requested a review. Let me know if it's OK with you. Thanks!

MNT: suggesting a list of code owners

---

sirepo_bluesky/tests/test_shadow_det.py

I believe there were changes on Radiasoft's side to fix the structure of the returned data for the `BeamStatisticsReport` plotting, so this PR addresses the change.

TST: fix the `BeamStatisticsReport` test (old API)

---

docs/source/release-history.rst

This is a summary of updates [since v0.4.1](https://github.com/NSLS-II/sirepo-bluesky/compare/v0.4.1...master).

DOC: release notes for v0.4.2

---

requirements.txt

This is a temporary fix of sirepo-bluesky tests failing with intake-0.6.5

Reverted temporarily to intake-0.6.4

---

.github/workflows/docs.yml
.github/workflows/publish-docs.yml
.github/workflows/testing.yml
sirepo_bluesky/sirepo_ophyd.py
sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py

This update computes the normal and tangential vector components on setting/putting to the `grazingAngle` component of the special mirrors, not the entire device.
The PR also updates the expected values of the components for 10 mrad per Sirepo response:
Closes #72.

Apply `.set()` to `grazingAngle` component, not device

---

service/etc/systemd/system/sirepo.service

To be installed into `/etc/systemd/system/sirepo.service` on the target RHEL8 machine.

Add systemd service unit for RHEL8

---

scripts/start_sirepo.sh
service/etc/systemd/system/sirepo.service

This should help with overfilled `/sirepo/` dir in the container.

Add env-vars to enable mounting of SIREPO_SRDB_ROOT dir on the host machine

---

.github/workflows/docs.yml
.github/workflows/flake8.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-pypi.yml
.github/workflows/testing.yml
docs/source/conf.py
requirements-dev.txt

This PR switches the docs theme to https://cloud-sptheme.readthedocs.io (inspired by https://psicode.org/psi4manual/master/). The new theme provides a bit more compact layout/text, and feels more modern.
Closes https://github.com/NSLS-II/sirepo-bluesky/issues/58.

DOC: use cloud theme for Sphinx

---

sirepo_bluesky/sirepo_ophyd.py

Read-only component, which may be used within https://github.com/NSLS-II-ARI/profile_sirepo_ari/pull/4.

Add `SirepoSignalRO`

---

.github/workflows/docs.yml
.github/workflows/pre-commit.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-pypi.yml
.github/workflows/testing.yml
.pre-commit-config.yaml
docs/build-table.py
requirements.txt
setup.py
sirepo_bluesky/__init__.py
sirepo_bluesky/sirepo_ophyd.py

This PR will help to unblock the latest versions of `sirepo-bluesky` to work with `tiled` (where intake should not be used).

Remove `intake` from the code base

---

docs/source/release-history.rst

The release notes for the upcoming release based on this range of commits:
https://github.com/NSLS-II/sirepo-bluesky/compare/v0.5.0...b3e4d906f99562595732a8806c265e52fa97df0a.

DOC: release notes for v0.6.0

---

docs/source/installation.rst

I updated the installation instructions file to clarify databroker configuration for macOS, Linux, and Windows. The second commit fixed some formatting. 
Closes #115

Updated Docs for Windows config of databroker - Resolves Issue #115 

---

requirements-dev.txt
requirements.txt

- `srwpy` minimum pin 4.0.0b1 to pick up some recent fixes
- `vcrpy` minumum pin 4.3.1 to fix the urllib v1/2 confusion
- add `xraylib` to disable a print about its unavailability while running examples, tests, etc.

PKG: Update dependencies

---

sirepo_bluesky/sirepo_ophyd.py

Sirepo reports all the simulation parameters as integers, though most of them should be floats. I changed the ophyd initialization just cast all the integers to floats. Probably this should be dealt with on the sirepo side at some point.

convert integer sirepo parameters to floats

---

sirepo_bluesky/shadow_handler.py
sirepo_bluesky/sirepo_ophyd.py
sirepo_bluesky/srw_handler.py
sirepo_bluesky/utils/__init__.py

Added a lightweight method that computes the beam position and FWHM before it's turned into a document. Now the beam stats show up in the callback!

Beam stats

---

docs/source/notebooks/elements.ipynb
docs/source/notebooks/madx.ipynb
sirepo_bluesky/sirepo_ophyd.py
sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py
sirepo_bluesky/tests/test_stateless_compute.py

- Added propagation parameters as ophyd objects. Examples of these can be found at https://github.com/radiasoft/sirepo/wiki/SRW-Propagation-Parameters
- Removed the sirepo_data parameter from create_classes as it was redundant.

Propagation parameters

---

.github/workflows/docs.yml
.pre-commit-config.yaml
docs/source/release-history.rst
requirements-dev.txt

* Generate beamline elements by @rlb131 in https://github.com/NSLS-II/sirepo-bluesky/pull/136
* Better way to prepare bluesky environment by @mrakitin in https://github.com/NSLS-II/sirepo-bluesky/pull/141
Also in this PR:
- includes a minimum pin of `sphinx` v7.2.2 due to https://github.com/pradyunsg/furo/discussions/693#discussioncomment-6753629
- change building docs with Python 3.10 as the missing `doct` v1.1.0 was published on PyPI: https://pypi.org/project/doct/1.1.0/.

DOC: release notes for v0.7.1

---

sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py

A simple fix to resolve failing runs on schedule.
A similar solution is implemented within #112 (we'll resolve the conflicts in that PR after merging this one).

TST: fix comparison of mean value of images with expected value
